# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'http://74.235.93.227:9000'
    scannerMode: 'MSBuild'
    projectKey: 'Only_Babes_BackEnd_AYu0lpurO3doOUDvEZWu'

# Run Code Analysis task
- task: SonarQubeAnalyze@4

# Publish Quality Gate Result task
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'
